name: Docker Image CI

on:
  workflow_call:
  workflow_dispatch:
  push:
    branches: [ main ]
    paths:
      - 'docker/**'
      - '.github/workflows/docker.yml'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to GHCR
      uses: docker/login-action@v1 
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
  
    - name: Build and push Docker images
      run: |
        git diff --name-only HEAD~ HEAD -- 'docker/*' | while read f; do
          filename=$(basename -- "$f")
          image_name="${filename%.*}" 
          docker build -t $image_name -f $f .
          docker tag $image_name ghcr.io/vincent-163/docker-images/$image_name
          docker push ghcr.io/vincent-163/docker-images/$image_name
        done
